# Exported from Render on 2026-07-04T20:45:07Z
version: "1"
projects:
- name: Render Deploy Fullstack
  environments:
  - name: Production
    services:
    - type: web
      name: render-deploy-frontend
      runtime: static
      repo: https://github.com/DavidMershon81/fullstack_deploy_template
      envVars:
      - key: .env
        sync: false
      buildCommand: npm install; npm run build
      staticPublishPath: dist
      autoDeployTrigger: commit
      rootDir: frontend
    - type: web
      name: render-deploy-api
      runtime: python
      repo: https://github.com/DavidMershon81/fullstack_deploy_template
      plan: free
      envVars:
      - key: .env
        sync: false
      region: oregon
      buildCommand: pip install uv && uv sync && uv run alembic upgrade head
      startCommand: uv run uvicorn main:app --host 0.0.0.0 --port 10000
      healthCheckPath: /health
      autoDeployTrigger: commit
      rootDir: api
    databases:
    - name: render-db
      databaseName: render_deploy_prod_db
      user: prod_db_user
      plan: free
      region: oregon
      ipAllowList: []
      postgresMajorVersion: "18"
